# Generated by Django 3.2.9 on 2021-12-31 08:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=75)),
                ('author_title', models.CharField(max_length=75)),
                ('mesage_from_author', models.TextField(max_length=1000)),
                ('about_author', models.TextField(max_length=1000)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author_image')),
                ('author_fb_link', models.URLField(max_length=500)),
                ('author_twitter_link', models.URLField(max_length=500)),
                ('author_google_link', models.URLField(max_length=500)),
                ('author_linkedin_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='courses_images')),
                ('course_details', models.TextField(default='', help_text='Please write a short description of the course')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to='courses.author')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_add_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=120)),
                ('reach_out_to_us_form_link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=75)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('video_description', models.TextField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_related_to_this_video', to='courses.course')),
            ],
        ),
    ]
