# Generated by Django 3.2.9 on 2021-12-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211219_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='auhor_name',
            new_name='author_name',
        ),
    ]
