# Generated by Django 3.2.9 on 2021-12-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_auhor_name_author_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_title',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
