# Generated by Django 3.2.9 on 2021-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_author_author_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=120)),
                ('reach_out_to_us_form_link', models.URLField(max_length=100)),
            ],
        ),
    ]
