# Generated by Django 3.2.9 on 2021-12-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211219_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
